name: CI

on: [push]

jobs:
  test:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"  # respect [ci skip] commit
    runs-on: ubuntu-latest
    env:
      SDSS_LOCAL_SAS_MIRROR: ./
      GAIA_TOOLS_DATA: ./
      LASMOT_DR5_DATA: ./
    strategy:
      fail-fast: false
      matrix:
        include:
          - { TF_VER: 1.15.5, TFP_VER: 0.8.0, ALLOW_FAILURE: false }
          - { TF_VER: 1.15.5, TFP_VER: 0.8.0, ALLOW_FAILURE: false }
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          pip install tensorflow==${{ matrix.TF_VER }}
          pip install tensorflow-probability==${{ matrix.TFP_VER }}
          pip install coveralls pytest pytest-cov
          python setup.py install
      - name: Test tfcannon
        continue-on-error: ${{ matrix.ALLOW_FAILURE }}
        if: ${{ matrix.PAPER_MODELS == false}}
        # Run almost all tests for latest config
        run: >
          python -m pytest --cov tfcannon --cov-report=xml tests
      - name: Upload coverage reports to Codecov
        continue-on-error: ${{ matrix.ALLOW_FAILURE }}
        uses: codecov/codecov-action@v1
        env:
          TF_VER: ${{ matrix.TF_VER }}
          TFP_VER: ${{ matrix.TFP_VER }}
        with:
          flags: unittests
          env_vars: TF_VER, TFP_VER
          name: codecov-tfcannon
          fail_ci_if_error: true
          verbose: true
